### ISSUE TITLE
Possible feature add for things such as EnterDocker

### ISSUE THREAD

**Issue by Guyverix** [joshuacox/roustabout#2]
I have been using your tools for over a year now, and they are GREAT!  thank you for providing these..  Thought you might want a possible feature-add for EnterDocker.

Not all containers have /bin/bash. so  I added an if clause to switch to /bin/sh if the previous exit code was not 0

Thought you might find it useful..

if [[ $? -gt 0 ]]; then
  docker exec -it $1 /bin/sh
fi
exit 0

**Comment by joshuacox** [comment]
@Guyverix thanks for the input!  All should be merged.  Let me know if you have any other ideas.  I'd also gladly help you make a merge/pull request so you get the credit in the code.
